"""initial migration

Revision ID: 20260514
Revises:
Create Date: 2026-05-14 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '20260514'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('email', sa.String(length=255), nullable=False),
        sa.Column('hashed_password', sa.String(length=255), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email')
    )
    op.create_index('ix_users_email', 'users', ['email'], unique=False)

    op.create_table('connections',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('connection_type', sa.Enum('source', 'target', 'jira', 'llm', name='connectiontype'), nullable=False),
        sa.Column('db_type', sa.Enum('postgresql', 'mysql', 'sqlserver', 'oracle', 'snowflake', 'bigquery', 'csv', 'parquet', name='dbtype'), nullable=True),
        sa.Column('encrypted_connection_string', sa.Text(), nullable=False),
        sa.Column('metadata', sa.JSON(), nullable=True),
        sa.Column('is_tested', sa.Boolean(), nullable=True),
        sa.Column('last_tested_at', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table('projects',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('status', sa.Enum('active', 'completed', 'archived', name='projectstatus'), nullable=True),
        sa.Column('current_phase', sa.Enum('input', 'discovery', 'propose', 'review', 'export', name='projectphase'), nullable=True),
        sa.Column('source_connection_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('target_connection_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('jira_connection_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('llm_connection_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('jira_ticket_key', sa.String(length=50), nullable=True),
        sa.Column('user_text_input', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['jira_connection_id'], ['connections.id'], ),
        sa.ForeignKeyConstraint(['llm_connection_id'], ['connections.id'], ),
        sa.ForeignKeyConstraint(['source_connection_id'], ['connections.id'], ),
        sa.ForeignKeyConstraint(['target_connection_id'], ['connections.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table('schema_cache',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('connection_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('project_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('object_type', sa.Enum('table', 'column', 'constraint', 'index', name='objecttype'), nullable=False),
        sa.Column('schema_name', sa.String(length=255), nullable=True),
        sa.Column('table_name', sa.String(length=255), nullable=True),
        sa.Column('column_name', sa.String(length=255), nullable=True),
        sa.Column('data_type', sa.String(length=255), nullable=True),
        sa.Column('is_nullable', sa.Boolean(), nullable=True),
        sa.Column('column_default', sa.Text(), nullable=True),
        sa.Column('sample_data', sa.JSON(), nullable=True),
        sa.Column('stats', sa.JSON(), nullable=True),
        sa.Column('fetched_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['connection_id'], ['connections.id'], ),
        sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table('mappings',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('project_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('target_connection_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('target_schema', sa.String(length=255), nullable=True),
        sa.Column('target_table', sa.String(length=255), nullable=False),
        sa.Column('target_column', sa.String(length=255), nullable=False),
        sa.Column('source_connection_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('source_schema', sa.String(length=255), nullable=True),
        sa.Column('source_table', sa.String(length=255), nullable=True),
        sa.Column('source_column', sa.String(length=255), nullable=True),
        sa.Column('business_logic', sa.Text(), nullable=True),
        sa.Column('transformation_rule', sa.Text(), nullable=True),
        sa.Column('confidence_score', sa.Numeric(precision=3, scale=2), nullable=True),
        sa.Column('status', sa.Enum('proposed', 'approved', 'rejected', 'modified', name='mappingstatus'), nullable=True),
        sa.Column('llm_reasoning', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
        sa.ForeignKeyConstraint(['source_connection_id'], ['connections.id'], ),
        sa.ForeignKeyConstraint(['target_connection_id'], ['connections.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table('mapping_feedback',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('mapping_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('user_action', sa.Enum('approved', 'rejected', 'modified', name='useraction'), nullable=False),
        sa.Column('user_notes', sa.Text(), nullable=True),
        sa.Column('original_proposal', sa.JSON(), nullable=True),
        sa.Column('final_state', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['mapping_id'], ['mappings.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table('jira_context',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('project_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('ticket_key', sa.String(length=50), nullable=False),
        sa.Column('ticket_summary', sa.Text(), nullable=True),
        sa.Column('ticket_description', sa.Text(), nullable=True),
        sa.Column('acceptance_criteria', sa.Text(), nullable=True),
        sa.Column('labels', sa.JSON(), nullable=True),
        sa.Column('fetched_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jira_context')
    op.drop_table('mapping_feedback')
    op.drop_table('mappings')
    op.drop_table('schema_cache')
    op.drop_table('projects')
    op.drop_table('connections')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
