"""add_inline_schema_support

Revision ID: 774374b3a14e
Revises: d9b91de58d7a
Create Date: 2026-05-16 10:42:30.425442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '774374b3a14e'
down_revision = 'd9b91de58d7a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('source_schemas', sa.JSON(), nullable=True))
    op.add_column('projects', sa.Column('target_schema', sa.JSON(), nullable=True))
    op.alter_column('schema_cache', 'connection_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('schema_cache', 'connection_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('projects', 'target_schema')
    op.drop_column('projects', 'source_schemas')
    # ### end Alembic commands ###
