"""add provider to connections

Revision ID: d9b91de58d7a
Revises: 20260514
Create Date: 2026-05-15 00:29:41.824136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9b91de58d7a'
down_revision = '20260514'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connections', sa.Column('provider', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('connections', 'provider')
    # ### end Alembic commands ###
